<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
            "child":[
                {
                    "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用户表管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用品分类管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"用品分类管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用品信息管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                ],
                "menu":"用品信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"出入库订单管理",
                        "menuJump":"列表",
                        "tableName":"inOutOrder"
                    }
                ],
                "menu":"出入库订单管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                        ],
                        "menu":"出入库订单详情管理",
                        "menuJump":"列表",
                        "tableName":"inOutOrderList"
                    }
                ],
                "menu":"出入库订单详情管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                        ],
                        "menu":"领用记录管理",
                        "menuJump":"列表",
                        "tableName":"jilu"
                    }
                ],
                "menu":"领用记录管理"
            }
        ],
        "frontMenu":[
        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
        "backMenu":[{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"用品分类管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"用品分类管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "领用",
                        ],
                        "menu":"用品信息管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
                ],
                "menu":"用品信息管理"
            },{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"领用记录管理",
                        "menuJump":"列表",
                        "tableName":"jilu"
                    }
                ],
                "menu":"领用记录管理"
            }
        ],
        "frontMenu":[
        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
